select * from [gold.dim_products]
select * from [gold.dim_customers]
select * from [gold.fact_sales]
--- selecting distinct category from the products
select distinct category from [gold.dim_products]

--- Exploring all countries the customer come from
select distinct country from [gold.dim_customers]

--- Exploring all categories "The major division"
select distinct category, subcategory, product_name from [gold.dim_products]
order by 1,2,3

-- find the date of the first and last order date
-- How many years of sales are available
select distinct order_date from [gold.fact_sales]

select 
MIN(order_date) as first_order_date,
max(order_date) as last_order_date,
datediff(year,min(order_date),max(order_date)) as order_range_years
from [gold.fact_sales]

-- find the youngest and oldest customer
select min(birthdate) as youngest_birthdate,
max(birthdate) as oldest_birthdate from [gold.dim_customers]

-- find the ages
select datediff(year, min(birthdate), getdate()) as youngest_age,
datediff(year, max(birthdate), getdate()) as oldest_age from [gold.dim_customers]

-- Calculating the key metrics
-- Find the Total Sales
-- Find the average selling price
-- Find the Total number of orders
-- Find the Total number of products
-- Find the total number of customers
-- Find the total number of customers that has placed an order

select sum(price) as Total_Sales from [gold.fact_sales]
select avg(price) as Avg_Price from [gold.fact_sales]
select count(distinct order_number) as Total_orders from [gold.fact_sales]
select count(product_id) as total_product from [gold.dim_products]
select count(customer_id) as total_customers from [gold.dim_customers]
select count( distinct customer_id) as customer_placed_order from [gold.dim_customers]
inner join [gold.fact_sales] on [gold.dim_customers].customer_key = [gold.fact_sales].customer_key

-- Generating a report that shows all key metrics of the business
select 'Total Sales' as measure_name, sum(price) as Total_Sales from [gold.fact_sales]
union all
select 'Average Price', avg(price) as Avg_Price from [gold.fact_sales]
union all
select 'Total Orders', count(distinct order_number) as Total_orders from [gold.fact_sales]
union all
select 'Total Products', count(product_id) as total_product from [gold.dim_products]
union all
select 'Total Customers', count(customer_id) as total_customers from [gold.dim_customers]
union all
select 'Customer that placed order', count( distinct customer_id) as customer_placed_order from [gold.dim_customers]
inner join [gold.fact_sales] on [gold.dim_customers].customer_key = [gold.fact_sales].customer_key

--Analysis
-- Find the total customers by countries
-- Find the total customers by gender
-- Find the total products by category
-- What is the average costs in each category?
-- What is the total revenue generated for each category?
-- Find total revenue generated by each customer
-- What is the distribution of sold items across countries?

-- Total customers by countries
select count(customer_id) as Total_customers, country from [gold.dim_customers]
group by country
order by count(customer_id)

-- Total customers by gender
select count(customer_id) as Total_customers, gender from [gold.dim_customers]
group by gender
order by count(customer_id)
-- Total product by category
select count(product_id) as Total_product, category from [gold.dim_products]
group by category
order by count(product_id)

-- Total revenue generated by each customer
select first_name, last_name, sum(sales_amount) as Total_revenue from [gold.fact_sales]
left join [gold.dim_customers]
on 
[gold.fact_sales].customer_key = [gold.dim_customers].customer_key
group by first_name, last_name
order by sum(sales_amount) desc

-- Total revenue generated for each category
select category, sum(sales_amount) as Total_revenue from [gold.dim_products]
left join [gold.fact_sales] on
[gold.dim_products].product_key = [gold.fact_sales].product_key
where category is not null
group by category

-- Average cost in each category
select category, avg(cost) as Average_cost from [gold.dim_products]
group by category
order by Average_cost desc

-- Which 5 products generate the highest revenue?
-- What are the 5 worst-performing products in terms of sales
-- Find the Top-10 customers who have generated the highest revenue
-- Find 3 customers with the fewest orders placed

-- 5 products that generate the highest revenue
select top 5 product_name, sum(sales_amount) as Revenue from [gold.dim_products]
left join [gold.fact_sales] on
[gold.dim_products].product_key = [gold.fact_sales].product_key
group by product_name
order by sum(sales_amount) desc

-- 5 worst performing products in terms of sales
select top 5 product_name, sum(sales_amount) as Revenue from [gold.dim_products]
left join [gold.fact_sales] on
[gold.dim_products].product_key = [gold.fact_sales].product_key
group by product_name
having sum(sales_amount) is not null
order by sum(sales_amount)

-- Using the window function to find 5 products that generate the highest revenue
select * from (
select product_name, sum(sales_amount) as Revenue,
row_number() over (order by sum(sales_amount) desc) as rank_products
from [gold.dim_products]
left join [gold.fact_sales] on
[gold.dim_products].product_key = [gold.fact_sales].product_key
group by product_name) as t
where rank_products <=5

-- Top 10 customers who have generated the highest revenue
select top 10 first_name, last_name, sum(sales_amount) as revenue from [gold.dim_customers]
left join [gold.fact_sales]
on [gold.dim_customers].customer_key = [gold.fact_sales].customer_key
group by first_name, last_name
order by revenue desc


select * from (
select first_name, last_name, sum(sales_amount) as revenue, row_number() over (order by sum(sales_amount) desc) as rank_no
from [gold.dim_customers]
left join [gold.fact_sales]
on [gold.dim_customers].customer_key = [gold.fact_sales].customer_key
group by first_name, last_name) t
where rank_no <=10

-- CHANGE OVER TIME
-- Analyzing how the measures evolves over time by tracking trends and identifying seasonality in the data.
select order_date, sales_amount from [gold.fact_sales]
where order_date is not null
order by order_date

select year(order_date) as Years, sum(sales_amount) as revenue from [gold.fact_sales]
where order_date is not null
group by year(order_date)
order by sum(sales_amount) desc

select year(order_date) as Years, sum(sales_amount) as revenue, count(distinct customer_key) as Total_customers
, sum(quantity) as Total_quantity from [gold.fact_sales]
where order_date is not null
group by year(order_date)
order by sum(sales_amount) desc

select datetrunc(month,order_date) as order_date, sum(sales_amount) as Total_sales, count(distinct customer_key) as Total_customers
, sum(quantity) as Total_quantity from [gold.fact_sales]
where order_date is not null
group by datetrunc(month,order_date)
order by datetrunc(month,order_date) desc

